import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ToastProvider } from '@/Providers/ToastProvider';
import { ConfettiProvider } from '@/Providers/ConfettiProvider';



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'E-LMS',
  description: 'Generated by create next app and developed by Michael',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ConfettiProvider />
          <ToastProvider />
          
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}